/*----------------------------------------------------------------------------*/
/* Copyright (c) FIRST 2008. All Rights Reserved.							  */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the FIRST BSD license file in $(WIND_BASE)/WPILib.  */
/*----------------------------------------------------------------------------*/

#ifndef SONAR_H_
#define SONAR_H_

#include "SensorBase.h"
#include "Task.h"
#include "PIDSource.h"

class Counter;
class DigitalInput;
class DigitalOutput;

/**
 * Sonar rangefinder class.
 * The Sonar rangefinder measures absolute distance based on the round-trip time
 * of a ping generated by the controller. These sensors use two transducers, a speaker and
 * a microphone both tuned to the sonar range. A common sonar sensor, the Daventech SRF04
 * requires a short pulse to be generated on a digital channel. This causes the chirp to be
 * emmitted. A second line becomes high as the ping is transmitted and goes low when
 * the echo is received. The time that the line is high determines the round trip distance
 * (time of flight).
 */
class Sonar: public SensorBase, public PIDSource
{
public:
	typedef enum {
		kInches = 0,
		kMilliMeters = 1
	} DistanceUnit;
	
	Sonar(DigitalOutput *pingChannel, DigitalInput *echoChannel, DistanceUnit units = kInches);
	Sonar(DigitalOutput &pingChannel, DigitalInput &echoChannel, DistanceUnit units = kInches);
	Sonar(UINT32 pingChannel, UINT32 echoChannel, DistanceUnit units = kInches);
	Sonar(UINT32 pingSlot, UINT32 pingChannel,
							UINT32 echoSlot, UINT32 echoChannel, DistanceUnit units = kInches);
	virtual ~Sonar();

	void Ping();
	bool IsRangeValid();
	static void SetAutomaticMode(bool enabling);
	double GetRangeInches();
	double GetRangeMM();
	bool IsEnabled() { return m_enabled; }
	void SetEnabled(bool enable) { m_enabled = enable; }
	
	double PIDGet();
	void SetDistanceUnits(DistanceUnit units);
	DistanceUnit GetDistanceUnits();

private:
	void Initialize();

	static void SonarChecker();

	static const double kPingTime = 10 * 1e-6;	///< Time (sec) for the ping trigger pulse.
	static const UINT32 kPriority = 90;	///< Priority that the sonar round robin task runs.
	static const double kMaxSonarTime = 0.1;	///< Max time (ms) between readings.
	static const double kSpeedOfSoundInchesPerSec = 1130.0 * 12.0;

	static Task m_task; // task doing the round-robin automatic sensing
	static Sonar *m_firstSensor; // head of the sonar sensor list
	static bool m_automaticEnabled; // automatic round robin mode
	static SEM_ID m_semaphore; // synchronize access to the list of sensors

	DigitalInput *m_echoChannel;
	DigitalOutput *m_pingChannel;
	bool m_allocatedChannels;
	bool m_enabled;
	Counter *m_counter;
	Sonar *m_nextSensor;
	
	DistanceUnit m_units;
};

#endif

